### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by SiddhiWandre** [naveen-9697/Handwritten-text-recognition-OCR----IAM-dataset---CNN-and-BiRNN#1]
![bug](https://user-images.githubusercontent.com/63348519/166821756-c2a022e0-c0c1-4fd5-b032-a9d8318b114b.jpg)

Getting an attribute error here, please check the attached image.
@naveen-marthala

**Comment by naveenmarthala** [comment]
can you give me the type(data type) of `train_files[i[0]`

**Comment by SiddhiWandre** [comment]
data type of train_files[i][0] is string

**Comment by naveenmarthala** [comment]
can you do 
```
i = 21
img_21 = cv2.imread(train_files[i][0])
print(type(img_21))
print(img_21)
```
and paste the output here?

**Comment by SiddhiWandre** [comment]
![bug2](https://user-images.githubusercontent.com/63348519/166985336-d646051a-984d-450b-bfa1-564c453fe70a.jpg)

**Comment by naveenmarthala** [comment]
does that not solve your issue then?
