### ISSUE TITLE
regarding data split

### ISSUE THREAD

**Issue by AniketGurav** [naveen-9697/Handwritten-text-recognition-OCR----IAM-dataset---CNN-and-BiRNN#2]
Hi, Naveen thanks for the work.

Could you please explain how you divided the IAM dataset for this repository?

Is this a new split you've made for the repository, or have you previously utilized an official split like the one described in the repository at https://github.com/shonenkov/IAM-Splitting,

There are 87K words in the training, 4K in each exam, and valid, as far as I can detect. My observation is this split probably does not correspond to any formal divide.

**Comment by naveenmarthala** [comment]
you are right that my splits do not correspond to any formal division. I do not remember how i had done the splits. i will get back to you.

**Comment by naveenmarthala** [comment]
they are random splits.

**Comment by AniketGurav** [comment]
Thanks for reply!!!
